### ISSUE TITLE
neon eventDate values do not conform to ISO8601 

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/source-neon#2]
In recent version of neon dwca, eventDate values like `7/10/13` are found. This format is not compatible with ISO 8601. Instead, values like 2013-07-10 are expected. 

An effect of this was that freshdata ignored recent neon archive version. Interestingly, the neon archive version of 17 August 2016 (see http://archive.effechecka.org/job/neon/24/) did have valid event dates. 

This issue is the root cause of https://github.com/gimmefreshdata/freshdata/issues/51 .

**Comment by jhammock** [comment]
I suspect this is what I get for editing in excel. It was trying to help. Anyway, I can be more vigilant...

**Comment by jhpoelen** [comment]
Thanks for making the changes. Please feel free to delete the older neon builds from the archive manager (only the successful ones will do). This way, fresh data no longer plows through the older records with the non-iso8601 date formats.
